# Generated by Django 5.2.8 on 2025-11-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='1 to 5 stars')),
            ],
        ),
    ]
